import os
from ast import literal_eval

from bef4llm.validation.validation import validate_bpmn
from bef4llm.process_models.importer.bpmn_importer import load_diagram_from_xml
from bef4llm.process_models.graph_representation.node_types import Gateway

def get_number_elements_per_model(llm_dir):
    """
    counts the number of elements that are in total used (per LLM)

    Parameters
    ----------
    llm_dir : str
        folder directory in which all BPMNs generated by the LLM are saved

    Returns
    -------
    elements_dict : dict
        element as key, number of elements as value
    """

    element_dict = dict()
    for dataset in os.listdir(llm_dir):
        if os.path.isfile(os.path.join(llm_dir, dataset)):
            continue

        for model in os.listdir(os.path.join(llm_dir, dataset)):

            if validate_bpmn(f"{llm_dir}/{dataset}/{model}"):
                element_dict[model] = dict()
                bpmn = load_diagram_from_xml(f"{llm_dir}/{dataset}/{model}")

                if bpmn.pools != {}:
                    element_dict[model]["pool"] = len(bpmn.pools)

                if bpmn.lanes != {}:
                    element_dict[model]["lane"] = len(bpmn.lanes)

                for node in bpmn.process_graph:
                    if bpmn.process_graph.nodes[node] != {}:
                        type = bpmn.process_graph.nodes[node]["type"]
                        if type in element_dict:
                            element_dict[model][type] += 1
                        else:
                            element_dict[model][type] = 1
            #except Exception as e:
                #print(model, e, e.args)

    return element_dict

def pools_and_lanes(target_dir):
    """
    Computes numbers concerning the usage of pools and lanes

    Parameters
    ----------
    target_dir : str
        directory where all BPMNs generated by the LLM are saved

    Returns
    -------
    models_with_lane: dict
        list of BPMN dirs of BPMNs that have at least one lane
    models_with_pool: dict
        list of BPMN dirs of BPMNs that have at least one pool
    models_without_gateway: dict
        list of BPMN dirs of BPMNs that do not contain any gateways
    """
    element_dict = get_number_elements_per_model(target_dir)

    models_with_pool = 0
    models_with_lane = 0
    model_without_gateway = 0
    for model in element_dict:
        if "pool" in element_dict[model]:
            models_with_pool += 1

        if "lane" in element_dict[model]:
            models_with_lane += 1


        if Gateway.complexGateway.value not in element_dict[model]\
            and Gateway.parallelGateway.value not in element_dict[model]\
            and Gateway.exclusiveGateway.value not in element_dict[model]\
            and Gateway.inclusiveGateway.value not in element_dict[model]\
            and Gateway.eventBasedGateway.value not in element_dict[model]:
            model_without_gateway += 1

    print(f"Total number of models {len(element_dict)}")
    print(f"Models with pool: {models_with_pool}")
    print(f"Models with lane: {models_with_lane}")
    print(f"Model without gateways: {model_without_gateway}")
    return models_with_lane, models_with_pool, model_without_gateway

"""
def correction_rates(llm_dir):
    for llm in os.listdir(llm_dir):
        print(llm)
        with open(f"{llm_dir}/{llm}/not_valid.txt", "r") as f:
            not_valid_bpmn_1 = literal_eval(f.read())

        with open(f"{llm_dir}/{llm}/not_modelled.txt", "r") as f:
            not_modelled = literal_eval(f.read())

        not_valid_bpmn_1 = [model for model in not_valid_bpmn_1 if model not in not_modelled]
        print(f"Not vaild first time: {len(not_valid_bpmn_1)}")

        not_valid_bpmn_2 = []
        for dataset in os.listdir(os.path.join(llm_dir, llm)):
            if not os.path.isfile(os.path.join(llm_dir, llm, dataset)):
                for model in os.listdir(os.path.join(llm_dir, llm, dataset)):
                    if not validate_bpmn(f"{llm_dir}/{llm}/{dataset}/{model}"):
                        not_valid_bpmn_2.append(model)

        print(f"Not vaild second time: {len(not_valid_bpmn_2)}")
        print(f"ratio: {len(not_valid_bpmn_2)/len(not_valid_bpmn_1)}")
"""